name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}

    strategy:
      # If true, cancel the workflow run if any matrix job fails.
      # If false, continue to run the workflow and complete all matrix jobs, even if one or more jobs fail.
      fail-fast: true

      matrix:
        include:
          - os: macos-latest
            runtime: osx-arm64
            output_name: snake-macos-arm64
            archive_name: snake-macos-arm64.tar.gz
            archive_type: tar
          - os: ubuntu-latest
            runtime: linux-x64
            output_name: snake-linux-x86_64
            archive_name: snake-linux-x86_64.tar.gz
            archive_type: tar
          - os: windows-latest
            runtime: win-x64
            output_name: snake-windows-x86_64.exe
            archive_name: snake-windows-x86_64.zip
            archive_type: zip

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ matrix.runtime }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        # Release configuration is the default since .NET 8 or a later.
        # See: https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-publish-config
        # We also explicitly enable Release mode in `Directory.Build.props`.
        run: dotnet publish

      - name: Rename binary
        # Rename the binary to match the platform.
        shell: bash
        run: mv publish/snake publish/${{ matrix.output_name }}

      - name: Archive Binary
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: ${{ matrix.archive_type }}
          filename: "${{ matrix.archive_name }}"
          directory: publish
          path: ${{ matrix.output_name }}

      - name: Release
        # Upload the binary to the release page.
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            publish/${{ matrix.archive_name }}
